[package]
name = "lmms2-exporter"
version = "0.1.0"
authors = ["Ray Redondo <rdredondo@lcdev.xyz>"]

edition.workspace = true
repository.workspace = true
license.workspace = true
categories.workspace = true

[dependencies]
lmms2-core = { path = "../core" }