[workspace]
members = ["core", "exporter", "gui/egui", "gui/iced"]
resolver = "2"

[workspace.package]
edition = "2021"
repository = "https://github.com/rdrpenguin04/rmms"
license = "GPL-3.0-or-later"
categories = ["multimedia::audio"]

[workspace.dependencies]
clap = "4"
cpal = "0.14"
flacenc = { git = "https://github.com/yotarok/flacenc-rs" }
quick-xml = "0.26"
rand = "0.8"
bitvec = "1"