[workspace]
members = ["core", "exporter", "gui"]
resolver = "2"

[workspace.package]
edition = "2021"
repository = "https://github.com/rdrpenguin04/lmms2"
license = "GPL-3.0-or-later"
categories = ["multimedia::audio"]

[workspace.dependencies]
clap = "4"
cpal = "0.14"
quick-xml = "0.26"
rand = "0.8"