[package]
name = "rmms-egui"
version = "0.1.0"
authors = ["Ray Redondo <rdredondo@lcdev.xyz>"]

edition.workspace = true
repository.workspace = true
license.workspace = true
categories.workspace = true

[dependencies]
rmms-core = { path = "../../core", features = ["cpal"] }
